# Generated by Django 3.2.3 on 2021-05-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='friendly_name',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
