# Generated by Django 3.2.3 on 2021-05-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_plan_friendly_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='features',
            new_name='long_description',
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(default='default', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='short_description',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
