# Generated by Django 3.2.3 on 2021-07-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_auto_20210525_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='access_times',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='disabled_access',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='extra_info',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='hours_incl',
            field=models.TextField(default='defualt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='wifi',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
