# Generated by Django 3.2.3 on 2021-07-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_auto_20210702_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='disabled_access',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='wifi',
            field=models.BooleanField(default=True),
        ),
    ]
