# Generated by Django 3.2.3 on 2021-07-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_auto_20210702_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='price_id',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
