# Generated by Django 3.2.3 on 2021-07-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_id',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
