# Generated by Django 3.2.3 on 2021-07-27 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_alter_order_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='password',
        ),
    ]
