# Generated by Django 3.2.3 on 2021-07-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_remove_order_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='password',
            field=models.CharField(default='default', max_length=25),
            preserve_default=False,
        ),
    ]
