# Generated by Django 3.2.3 on 2021-07-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_order_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='password',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
