# Generated by Django 3.2.3 on 2021-07-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='lat',
            field=models.FloatField(default=56.78, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locations',
            name='lng',
            field=models.FloatField(default=-34.67, max_length=10),
            preserve_default=False,
        ),
    ]
